# Generated by Django 3.0.8 on 2020-07-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'ชาย'), ('female', 'หญิง')], max_length=6)),
                ('year', models.CharField(max_length=6)),
                ('faculty', models.CharField(max_length=255)),
            ],
        ),
    ]
