# Generated by Django 3.0.8 on 2020-07-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='employee_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
